source 'https://rubygems.org'

gem 'dashing'

## Remove this if you don't need a twitter widget.
##gem 'twitter', '>= 5.9.0'
## gem 'execjs', '1.4.0'

source "https://rubygems.org"
ruby "2.0.0"
gem 'sinatra', '1.1.0'